name: Auto-sync
on:
  schedule:
    - cron: '30 05 * * *'
  workflow_dispatch:

jobs:
  do_sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync xtuml/conan-center-index -b master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
